package com.tp.mes.app.notice.config;

import com.tp.mes.support.OracleErrorSupport;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class NoticeSchemaInitializer {

    private final JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void initSchema() {
        log.info("Checking Notice schema...");
        initTable("notice",
                "create table notice (" +
                        "  notice_id number generated by default on null as identity," +
                        "  title varchar2(200) not null," +
                        "  body clob," +
                        "  created_by number," +
                        "  created_at timestamp default systimestamp not null," +
                        "  constraint pk_notice primary key (notice_id)," +
                        "  constraint fk_notice_created_by foreign key (created_by) references app_user(user_id)" +
                        ")");
        log.info("Notice schema check complete.");
    }

    private void initTable(String tableName, String ddl) {
        try {
            jdbcTemplate.execute("SELECT 1 FROM " + tableName + " WHERE 1=0");
        } catch (DataAccessException ex) {
            if (OracleErrorSupport.isMissingTableOrView(ex)) {
                log.info("Table {} not found. Creating...", tableName);
                try {
                    jdbcTemplate.execute(ddl);
                    log.info("Table {} created successfully.", tableName);
                    seedNotice();
                } catch (DataAccessException createEx) {
                    log.error("Failed to create table {}: {}", tableName, createEx.getMessage());
                }
            } else {
                log.warn("Error checking table {}: {}", tableName, ex.getMessage());
            }
        }
    }

    private void seedNotice() {
        try {
            // Dummy seed
            jdbcTemplate.execute(
                    "INSERT INTO notice (title, body, created_at) VALUES ('Welcome to MES', 'System initialization complete. Welcome to the Manufacturing Execution System.', SYSTIMESTAMP)");
        } catch (Exception e) {
            log.warn("Failed to seed notice: {}", e.getMessage());
        }
    }
}
