package com.tp.mes.app.prod.config;

import com.tp.mes.support.OracleErrorSupport;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Initializes production schema tables if they are missing.
 * This ensures the application works out-of-the-box even if oracle-init.sql
 * hasn't been run fully.
 */
@Component
public class ProductionSchemaInitializer {

    private static final Logger log = LoggerFactory.getLogger(ProductionSchemaInitializer.class);
    private final JdbcTemplate jdbcTemplate;

    public ProductionSchemaInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    public void init() {
        log.info("Checking production schema...");

        // 1. Production Process
        initTable("production_process",
                "create table production_process (" +
                        "  process_id number generated by default on null as identity," +
                        "  process_code varchar2(40) not null," +
                        "  process_name varchar2(200) not null," +
                        "  constraint pk_production_process primary key (process_id)," +
                        "  constraint uq_production_process_code unique (process_code)" +
                        ")");

        // Seed processes if table was just created or empty
        seedProcesses();

        // 2. Equipment (depends on process)
        initTable("equipment",
                "create table equipment (" +
                        "  equipment_id number generated by default on null as identity," +
                        "  equipment_code varchar2(40) not null," +
                        "  equipment_name varchar2(200) not null," +
                        "  process_id number," +
                        "  active_yn char(1) default 'Y' not null," +
                        "  constraint pk_equipment primary key (equipment_id)," +
                        "  constraint uq_equipment_code unique (equipment_code)," +
                        "  constraint fk_equipment_process foreign key (process_id) references production_process(process_id),"
                        +
                        "  constraint ck_equipment_active_yn check (active_yn in ('Y','N'))" +
                        ")");

        // 3. Production Plan
        initTable("production_plan",
                "create table production_plan (" +
                        "  plan_id number generated by default on null as identity," +
                        "  plan_date date not null," +
                        "  item_code varchar2(60) not null," +
                        "  qty_plan number(12,2) not null," +
                        "  created_by number," +
                        "  created_at timestamp default systimestamp not null," +
                        "  constraint pk_production_plan primary key (plan_id)," +
                        "  constraint fk_production_plan_created_by foreign key (created_by) references app_user(user_id)"
                        +
                        ")");

        // 4. Production Result
        initTable("production_result",
                "create table production_result (" +
                        "  result_id number generated by default on null as identity," +
                        "  work_date date not null," +
                        "  item_code varchar2(60) not null," +
                        "  qty_good number(12,2) default 0 not null," +
                        "  qty_ng number(12,2) default 0 not null," +
                        "  equipment_id number," +
                        "  created_by number," +
                        "  created_at timestamp default systimestamp not null," +
                        "  constraint pk_production_result primary key (result_id)," +
                        "  constraint fk_production_result_equipment foreign key (equipment_id) references equipment(equipment_id),"
                        +
                        "  constraint fk_production_result_created_by foreign key (created_by) references app_user(user_id)"
                        +
                        ")");

        log.info("Production schema check complete.");
    }

    private void initTable(String tableName, String ddl) {
        try {
            jdbcTemplate.execute("SELECT 1 FROM " + tableName + " WHERE 1=0");
            // Check if equipment needs seeding (if table exists but empty)
            if ("equipment".equalsIgnoreCase(tableName)) {
                seedEquipment();
            }
        } catch (DataAccessException ex) {
            if (OracleErrorSupport.isMissingTableOrView(ex)) {
                log.info("Table {} not found. Creating...", tableName);
                try {
                    jdbcTemplate.execute(ddl);
                    log.info("Table {} created successfully.", tableName);

                    if ("production_process".equalsIgnoreCase(tableName)) {
                        seedProcesses();
                    } else if ("equipment".equalsIgnoreCase(tableName)) {
                        seedEquipment();
                    }
                } catch (DataAccessException createEx) {
                    log.error("Failed to create table {}: {}", tableName, createEx.getMessage());
                }
            } else {
                // Different error
                log.warn("Error checking table {}: {}", tableName, ex.getMessage());
            }
        }
    }

    private void seedProcesses() {
        try {
            Integer count = jdbcTemplate.queryForObject("SELECT count(*) FROM production_process", Integer.class);
            if (count != null && count == 0) {
                log.info("Seeding production_process data...");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-01', '원자재 입고 및 검사')");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-02', '1차 가공 (절단/성형)')");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-03', '2차 가공 (열처리/도금)')");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-04', '부품 조립')");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-05', '최종 조립')");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-06', '성능 테스트')");
                jdbcTemplate.execute(
                        "INSERT INTO production_process (process_code, process_name) VALUES ('PROC-07', '최종 검사 및 포장')");
                log.info("Seeding complete.");
            }
        } catch (DataAccessException e) {
            log.warn("Failed to seed processes: {}", e.getMessage());
        }
    }

    private void seedEquipment() {
        try {
            Integer count = jdbcTemplate.queryForObject("SELECT count(*) FROM equipment", Integer.class);
            if (count != null && count == 0) {
                log.info("Seeding equipment data...");
                // Assuming process_ids 1-7 exist from seedProcesses
                jdbcTemplate.execute(
                        "INSERT INTO equipment (equipment_code, equipment_name, process_id, active_yn) VALUES ('EQ-01', '절단기 1호', 2, 'Y')");
                jdbcTemplate.execute(
                        "INSERT INTO equipment (equipment_code, equipment_name, process_id, active_yn) VALUES ('EQ-02', '성형기 1호', 2, 'Y')");
                jdbcTemplate.execute(
                        "INSERT INTO equipment (equipment_code, equipment_name, process_id, active_yn) VALUES ('EQ-03', '열처리로 A', 3, 'Y')");
                jdbcTemplate.execute(
                        "INSERT INTO equipment (equipment_code, equipment_name, process_id, active_yn) VALUES ('EQ-04', '조립 라인 1', 4, 'Y')");
                jdbcTemplate.execute(
                        "INSERT INTO equipment (equipment_code, equipment_name, process_id, active_yn) VALUES ('EQ-05', '성능 테스터', 6, 'N')"); // Stopped
                                                                                                                                             // example
                log.info("Seeding equipment complete.");
            }
        } catch (DataAccessException e) {
            log.warn("Failed to seed equipment: {}", e.getMessage());
        }
    }
}
