-- =============================================================
-- Autonomous Overhaul Script for MES System
-- =============================================================

-- 1. Create Materials Table
CREATE TABLE materials (
  material_id VARCHAR2(50) NOT NULL,
  material_name VARCHAR2(100) NOT NULL,
  current_stock NUMBER(12,2) DEFAULT 0,
  safe_stock_qty NUMBER(12,2) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_materials PRIMARY KEY (material_id)
);

-- Seed Materials
INSERT INTO materials (material_id, material_name, current_stock, safe_stock_qty) VALUES ('MAT-001', 'Aluminum Sheet', 1000, 100);
INSERT INTO materials (material_id, material_name, current_stock, safe_stock_qty) VALUES ('MAT-002', 'Plastic Resin', 500, 50);
INSERT INTO materials (material_id, material_name, current_stock, safe_stock_qty) VALUES ('MAT-003', 'Screw Set', 10000, 1000);

-- 2. Create Product BOM Table
CREATE TABLE product_bom (
  bom_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  product_item_code VARCHAR2(60) NOT NULL,
  material_inventory_id VARCHAR2(50) NOT NULL,
  quantity_required NUMBER(12,4) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_product_bom PRIMARY KEY (bom_id),
  CONSTRAINT fk_bom_material FOREIGN KEY (material_inventory_id) REFERENCES materials(material_id)
);

-- Seed BOM
INSERT INTO product_bom (product_item_code, material_inventory_id, quantity_required) VALUES ('ITEM-A', 'MAT-001', 2.5);
INSERT INTO product_bom (product_item_code, material_inventory_id, quantity_required) VALUES ('ITEM-A', 'MAT-003', 10);
INSERT INTO product_bom (product_item_code, material_inventory_id, quantity_required) VALUES ('ITEM-B', 'MAT-002', 1.0);

-- 3. Alter Equipment Table
ALTER TABLE equipment ADD (last_start_time TIMESTAMP);
ALTER TABLE equipment ADD (total_run_time NUMBER DEFAULT 0);
