UPDATE TP_EQUIPMENT SET STATUS = 'STOPPED' WHERE STATUS IS NULL
/
UPDATE TP_EQUIPMENT SET UTILIZATION_RATE = 0 WHERE UTILIZATION_RATE IS NULL
/
UPDATE TP_EQUIPMENT SET OEE = 0 WHERE OEE IS NULL
/
COMMIT
/
