create table production_plan (
  plan_id number generated by default on null as identity,
  plan_date date not null,
  item_code varchar2(60) not null,
  qty_plan number(12,2) not null,
  created_by number,
  created_at timestamp default systimestamp not null,
  constraint pk_production_plan primary key (plan_id)
)
/
create table production_result (
  result_id number generated by default on null as identity,
  work_date date not null,
  item_code varchar2(60) not null,
  qty_good number(12,2) default 0 not null,
  qty_ng number(12,2) default 0 not null,
  equipment_id number,
  created_by number,
  created_at timestamp default systimestamp not null,
  constraint pk_production_result primary key (result_id)
)
/
