-- Operation Analytics & Inventory Tracking Schema
-- Run after oracle-init.sql and oracle-hrm.sql

-- 1. Materials (Raw Materials)
CREATE TABLE materials (
    material_id VARCHAR2(50) NOT NULL,
    material_name VARCHAR2(100) NOT NULL,
    current_stock NUMBER(12, 2) DEFAULT 0 NOT NULL,
    unit VARCHAR2(20) DEFAULT 'EA', -- EA, KG, L
    cost_per_unit NUMBER(12, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_materials PRIMARY KEY (material_id)
);

-- 2. Product BOM (Bill of Materials)
-- Maps Product Item Code (from production_plan/result) to required Materials
CREATE TABLE product_bom (
    bom_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_item_code VARCHAR2(60) NOT NULL, -- Logical link to items
    material_inventory_id VARCHAR2(50) NOT NULL, -- FK to materials.material_id
    quantity_required NUMBER(10, 4) NOT NULL, -- Amount of material per 1 unit of product
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_product_bom PRIMARY KEY (bom_id),
    CONSTRAINT fk_product_bom_material FOREIGN KEY (material_inventory_id) REFERENCES materials(material_id)
);

-- 3. Equipment History (Utilization Tracking)
-- Logs status changes (RUNNING, STOPPED, IDLE, ERROR)
CREATE TABLE equipment_history (
    history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    equipment_id NUMBER NOT NULL, -- FK to equipment.equipment_id (existing table)
    status VARCHAR2(20) NOT NULL, -- RUNNING, STOPPED, IDLE, ERROR
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP, -- NULL means currently active
    duration_seconds NUMBER(12, 0), -- Calculated when end_time is set
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_equipment_history PRIMARY KEY (history_id),
    CONSTRAINT fk_equipment_history_eq FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id)
);

-- Seed Data for Demo

-- Materials
INSERT INTO materials (material_id, material_name, current_stock, unit, cost_per_unit) 
VALUES ('MAT-STEEL-01', 'Steel Sheet 5mm', 1000, 'EA', 50000);

INSERT INTO materials (material_id, material_name, current_stock, unit, cost_per_unit) 
VALUES ('MAT-SCREW-01', 'M5 Screw', 50000, 'EA', 10);

INSERT INTO materials (material_id, material_name, current_stock, unit, cost_per_unit) 
VALUES ('MAT-PAINT-BLK', 'Black Paint', 200, 'L', 15000);

-- BOM for a sample product (e.g., 'PROD-001')
INSERT INTO product_bom (product_item_code, material_inventory_id, quantity_required)
VALUES ('PROD-001', 'MAT-STEEL-01', 1); -- 1 Steel Sheet per Product

INSERT INTO product_bom (product_item_code, material_inventory_id, quantity_required)
VALUES ('PROD-001', 'MAT-SCREW-01', 12); -- 12 Screws per Product

INSERT INTO product_bom (product_item_code, material_inventory_id, quantity_required)
VALUES ('PROD-001', 'MAT-PAINT-BLK', 0.5); -- 0.5L Paint per Product

COMMIT;
