-- Create minimal tables for MVC portfolio pages
-- Run this as a user that owns the schema (e.g. SYSTEM for demo, but prefer a dedicated user).

-- ===== Skills =====
create table skill (
  skill_id number generated by default on null as identity,
  skill_name varchar2(100) not null,
  sort_order number,
  constraint pk_skill primary key (skill_id),
  constraint uq_skill_name unique (skill_name)
);

-- ===== Projects =====
create table project (
  project_id number generated by default on null as identity,
  title varchar2(200) not null,
  stack varchar2(200) not null,
  sort_order number,
  constraint pk_project primary key (project_id)
);

create table project_highlight (
  highlight_id number generated by default on null as identity,
  project_id number not null,
  highlight varchar2(400) not null,
  sort_order number,
  constraint pk_project_highlight primary key (highlight_id),
  constraint fk_project_highlight_project foreign key (project_id) references project(project_id)
);

-- ===== Company Keywords =====
create table company_keyword (
  keyword_id number generated by default on null as identity,
  keyword varchar2(100) not null,
  sort_order number,
  constraint pk_company_keyword primary key (keyword_id),
  constraint uq_company_keyword unique (keyword)
);

-- ===== Company sections (menu + content) =====
create table company_section (
  section_id number generated by default on null as identity,
  category varchar2(100) not null,
  title varchar2(200) not null,
  anchor varchar2(80) not null,
  body varchar2(2000) not null,
  sort_order number,
  constraint pk_company_section primary key (section_id),
  constraint uq_company_section_anchor unique (anchor)
);

-- ===== Internal web system (Auth / Roles) =====
create table app_user (
  user_id number generated by default on null as identity,
  username varchar2(50) not null,
  password_hash varchar2(200) not null,
  display_name varchar2(100),
  enabled_yn char(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_app_user primary key (user_id),
  constraint uq_app_user_username unique (username),
  constraint ck_app_user_enabled_yn check (enabled_yn in ('Y','N'))
);

create table app_role (
  role_id number generated by default on null as identity,
  role_code varchar2(50) not null,
  constraint pk_app_role primary key (role_id),
  constraint uq_app_role_code unique (role_code)
);

create table app_user_role (
  user_id number not null,
  role_id number not null,
  constraint pk_app_user_role primary key (user_id, role_id),
  constraint fk_app_user_role_user foreign key (user_id) references app_user(user_id),
  constraint fk_app_user_role_role foreign key (role_id) references app_role(role_id)
);

-- ===== Group company management =====
create table group_company (
  company_id number generated by default on null as identity,
  company_code varchar2(40) not null,
  company_name varchar2(200) not null,
  description varchar2(1000),
  active_yn char(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_group_company primary key (company_id),
  constraint uq_group_company_code unique (company_code),
  constraint ck_group_company_active_yn check (active_yn in ('Y','N'))
);

-- ===== Notices / board =====
create table notice (
  notice_id number generated by default on null as identity,
  title varchar2(200) not null,
  body varchar2(4000) not null,
  created_by number,
  created_at timestamp default systimestamp not null,
  constraint pk_notice primary key (notice_id),
  constraint fk_notice_created_by foreign key (created_by) references app_user(user_id)
);

create table board_post (
  post_id number generated by default on null as identity,
  title varchar2(200) not null,
  body varchar2(4000) not null,
  created_by number,
  created_at timestamp default systimestamp not null,
  constraint pk_board_post primary key (post_id),
  constraint fk_board_post_created_by foreign key (created_by) references app_user(user_id)
);

-- ===== Production (MVP) =====
create table production_process (
  process_id number generated by default on null as identity,
  process_code varchar2(40) not null,
  process_name varchar2(200) not null,
  constraint pk_production_process primary key (process_id),
  constraint uq_production_process_code unique (process_code)
);

create table equipment (
  equipment_id number generated by default on null as identity,
  equipment_code varchar2(40) not null,
  equipment_name varchar2(200) not null,
  process_id number,
  active_yn char(1) default 'Y' not null,
  constraint pk_equipment primary key (equipment_id),
  constraint uq_equipment_code unique (equipment_code),
  constraint fk_equipment_process foreign key (process_id) references production_process(process_id),
  constraint ck_equipment_active_yn check (active_yn in ('Y','N'))
);

create table production_plan (
  plan_id number generated by default on null as identity,
  plan_date date not null,
  item_code varchar2(60) not null,
  qty_plan number(12,2) not null,
  created_by number,
  created_at timestamp default systimestamp not null,
  constraint pk_production_plan primary key (plan_id),
  constraint fk_production_plan_created_by foreign key (created_by) references app_user(user_id)
);

create table production_result (
  result_id number generated by default on null as identity,
  work_date date not null,
  item_code varchar2(60) not null,
  qty_good number(12,2) default 0 not null,
  qty_ng number(12,2) default 0 not null,
  equipment_id number,
  created_by number,
  created_at timestamp default systimestamp not null,
  constraint pk_production_result primary key (result_id),
  constraint fk_production_result_equipment foreign key (equipment_id) references equipment(equipment_id),
  constraint fk_production_result_created_by foreign key (created_by) references app_user(user_id)
);
-- Insert Production Processes if empty
MERGE INTO production_process p
USING (
    SELECT 1 as id, 'PROC-01' as code, '원자재 입고 및 검사' as name FROM DUAL UNION ALL
    SELECT 2, 'PROC-02', '1차 가공 (절단/성형)' FROM DUAL UNION ALL
    SELECT 3, 'PROC-03', '2차 가공 (열처리/도금)' FROM DUAL UNION ALL
    SELECT 4, 'PROC-04', '부품 조립' FROM DUAL UNION ALL
    SELECT 5, 'PROC-05', '최종 조립' FROM DUAL UNION ALL
    SELECT 6, 'PROC-06', '성능 테스트' FROM DUAL UNION ALL
    SELECT 7, 'PROC-07', '최종 검사 및 포장' FROM DUAL
) s
ON (p.process_code = s.code)
WHEN NOT MATCHED THEN
    INSERT (process_id, process_code, process_name)
    VALUES (s.id, s.code, s.name);

COMMIT;
